<a href="https://colab.research.google.com/github/MikeChastain84/Mike_INFO5731_Fall2024/blob/main/Chastain_Mike_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 In-class Exercise 3**

The purpose of this exercise is to explore various aspects of text analysis, including feature extraction, feature selection, and text similarity ranking.

**Expectations**:
*   Use the provided .*ipynb* document to write your code & respond to the questions. Avoid generating a new file.
*   Write complete answers and run all the cells before submission.
*   Make sure the submission is "clean"; *i.e.*, no unnecessary code cells.
*   Once finished, allow shared rights from top right corner (*see Canvas for details*).

**Total points**: 40

**Deadline**: This in-class exercise is due at the end of Friday, at 11:59 PM.

**Late submissions will have a penalty of 10% of the marks for each day of late submission. , and no requests will be answered. Manage your time accordingly.**

**Please check that the link you submitted can be opened and points to the correct assignment.**

## Question 1 (10 Points)
Describe an interesting **text classification or text mining task** and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features. **Your dataset must be text.**

In [30]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

Spam detection would be an interesting text classification model.

Features:
1. Bag of Words. Spam messages like to create a sense of urgency or provide an incintive to encourage a user to take an action
    such as respond to a message or click a link. By counting the word occurances for words commonly used to create a sense of urgency
    or incintivize a user (prize, win, "must act now," etc.) you can begin to determine the likelihood of a message being spam.

2. Presence of links, URL, and especially short URLs. A feature that checks for the presence of URLs would be affective.

3. TF-IDF could be used to identify the importance of words in a message. When multiple words commonly use in spam (offer, win, urgent) are
    identified in the message, it's likely to be spam.

4. Linguistic features can help an ML model identify identify language patterns common to spam. Spam messages try to entice users to take an
    action phrases such as "act now," "take action," "limited time," etc. Linguistic features can help identify these language patterns.

5. Message length. Spam messages are usally around the same length. They're usually short and to the point or lengthy. These could be used
    to flag a message as potential spam.

6. Unknown sender. I don't know how, but if you can check the sender against the receivers known contact this could prove useful. Spam
    messages usually originate from an unknown sender.

7. Poor grammar. Spam messages often contain poor grammar combined with a sense of urgency. Being able to detect poor grammar could be helpful.
'''

'\nPlease write you answer here:\n\nSpam detection would be an interesting text classification model.\n\nFeatures:\n1. Bag of Words. Spam messages like to create a sense of urgency or provide an incintive to encourage a user to take an action \n    such as respond to a message or click a link. By counting the word occurances for words commonly used to create a sense of urgency \n    or incintivize a user (prize, win, "must act now," etc.) you can begin to determine the likelihood of a message being spam.\n\n2. Presence of links, URL, and especially short URLs. A feature that checks for the presence of URLs would be affective.\n\n3. TF-IDF could be used to identify the importance of words in a message. When multiple words commonly use in spam (offer, win, urgent) are \n    identified in the message, it\'s likely to be spam.\n\n4. Linguistic features can help an ML model identify identify language patterns common to spam. Spam messages try to entice users to take an\n    action phrases s

## Question 2 (10 Points)
Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [29]:
# You code here (Please add comments in the code):

# 1. Bag of Words (BOW):
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Create messages to serve as test data:
messages = [
    "Win a free ipad. Click this link.",                    # Spam
    "Limited time offer! Click here to claim your prize.",  # Spam
    "Hello, are you there?",                                # Not spam
    "Hurry now to claim your prize!",                       # Spam
    "What are you doing?"                                   # Not spam
]

# Bag of words: Initialize the object vect. The first instance of the tool, CountVectorizer().
vect = CountVectorizer()

# Get counts of each token in the text data. Store this as a sparse array in x.
x = vect.fit_transform(messages)

# Converts sparse array to a dense array
x.toarray()

# view token vocabulary and counts
print("1. Bag of Words Results:")
print("vocabulary", vect.vocabulary_)
print("shape", x.shape)
print("vectors: ", x.toarray())

# """
# Common spam words: win, free, ipad, click, link, limited, time, offer, claim, prize, hurry

# From my output:

# First message ([0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0]):
# Contains 4 common spam words: "win", "free", "click", "link"
# These words are strong indicators of spam. This message is likely spam.

# Second message ([0 1 1 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 1]):
# Contains 5 common spam words: "claim", "click", "prize", "limited", "time"
# These words are strong indicators of spam. This message is likely spam.

# Third message ([1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0]):
# Contains: "hello", "are", "there", "you"
# These are words are found in regular conversations. This message not likely to be spam.

# Fourth message ([0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 1]):
# Contains 4 common spam words: "claim", "prize", "hurry", "now"
# These words are strong indicators of spam. This message is likely spam.

# Fifth message ([1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]):
# Contains: "what", "doing", "you"
# These are words are found in regular conversations. This message not likely to be spam.
# """

# 2. Presence of links or URLs:
import re

# define a function to detect URLs using regex:
def contains_url(text):
  url_pattern = r'(https?://\S+|www\.\S+)'          # Regular expression to match URLs
  return 1 if re.search(url_pattern, text) else 0   # 1 - URL present; 0 - no URL

# apply contains_url() function to messages
url_feature = [contains_url(message) for message in messages]

# create dataframe to display with URL feature
df = pd.DataFrame({'Message': messages, 'URL': url_feature})

# display dataframe
print("\n2. Presence of links or URLs Results:")
print(df)

# 3. TF-IDF:

# Import Libraries
from sklearn.feature_extraction.text import TfidfVectorizer   # Imports the TF-IDF Vectorizer class

# Create an instance (object) of the TfidfVectorizer class. This will be used to convert the text data into a matrix of TF-IDF scores.
TFIDF = TfidfVectorizer(min_df=1, ngram_range=(1, 2))
    # min_df=1 - include any word (or term) that appears in at least one document
    # ngram_range=(1, 2) - consider both single words (1-grams) and pairs of consecutive words (2-grams) as features

# Convert the text data into a sparse matrix of TF-IDF scores. Each row is a document. Each column is a word or word pair.
# ...The values in the matrix are the TF-IDF scores for those words in each document.
features = TFIDF.fit_transform(messages)

# Converts sparse matrix data to dense matrix and saves it as "df_tfidf"
df_tfidf = pd.DataFrame(
    features.todense(),                   # applies todense() to the features matrix converting it to a dense matrix
    columns=TFIDF.get_feature_names_out() # gets the list of words (n-grams) and uses them to label the columns
    )

# Display the TF-IDF matrix
print("\n3. TF-IDF Results:")
print(df_tfidf)


# Common spam words: win, free, ipad, click, link, limited, time, offer, claim, prize, hurry

# From the 3.TF-IDF Results below:

# Each row represents a message.
# 0: "Win a free iPad. Click this link." (Spam)
# 1: "Limited time offer! Click here to claim your prize." (Spam)
# 2: "Hello, are you there?" (Not spam)
# 3: "Hurry now to claim your prize!" (Spam)
# 4: "What are you doing?" (Not spam)

# Each column represents a word or word pair as labeled by the TF-IDF Vectorizer.
# The values in the matrix are the TF-IDF scores for those words in each message.

# The messages with high scores aligned with the common spam words list are 0, 1, and 3.
# These messages are likely to be spam.

# The messages with low scores aligned with the common spam words list are 2 and 4.
# These messages are not likely to be spam.

1. Bag of Words Results:
vocabulary {'win': 19, 'free': 4, 'ipad': 8, 'click': 2, 'this': 15, 'link': 10, 'limited': 9, 'time': 16, 'offer': 12, 'here': 6, 'to': 17, 'claim': 1, 'your': 21, 'prize': 13, 'hello': 5, 'are': 0, 'you': 20, 'there': 14, 'hurry': 7, 'now': 11, 'what': 18, 'doing': 3}
shape (5, 22)
vectors:  [[0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0]
 [0 1 1 0 0 0 1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 1]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 1]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0]]

2. Presence of links or URLs Results:
                                             Message  URL
0                  Win a free ipad. Click this link.    0
1  Limited time offer! Click here to claim your p...    0
2                              Hello, are you there?    0
3                     Hurry now to claim your prize!    0
4                                What are you doing?    0

3. TF-IDF Results:
        are   are you     claim  clai

## Question 3 (10 points):
Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [31]:
# You code here (Please add comments in the code):
# First, import necessary libraries and tools:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_selection import chi2                  # I selected chi-squared test
import pandas as pd

# Next, create messages for test data and labels (spam = 1, not spam = 0)
messages = [
    "Win a free ipad. Click this link.",                    # Spam
    "Limited time offer! Click here to claim prize.",       # Spam
    "Hello, are you there?",                                # Not spam
    "Hurry now to claim prize!",                            # Spam
    "Click this link to claim a rare prize!",               # Spam
    "What are you doing?"                                   # Not spam
]

# Create labels:
labels = [1, 1, 0, 1, 1, 0]                                    # spam = 1, not spam = 0

# Vectorize the messages using CountVectorizer():
vect = CountVectorizer()
x = vect.fit_transform(messages)

# Apply the chi-squared test to the word counts and labels:
chi2_scores, p_values = chi2(x, labels)

# Create a data frame using pandas with feature names, Chi-square scores, and p-values:
feature_names = vect.get_feature_names_out()
chi2_df = pd.DataFrame({'Feature': feature_names,   # column for feature names (words)
                        'Chi-square': chi2_scores,  # column for Chi-square scores
                        'p-value': p_values})       # column for p-values

# Sort in descending order by Chi-square score:
chi2_df_sorted = chi2_df.sort_values(by='Chi-square', ascending=True)

# Display the results:
print("Chi-square Results:")
print(chi2_df_sorted.head(10))  # print the top 10

Chi-square Results:
    Feature  Chi-square  p-value
9   limited         0.5   0.4795
17     time         0.5   0.4795
14     rare         0.5   0.4795
4      free         0.5   0.4795
12    offer         0.5   0.4795
6      here         0.5   0.4795
7     hurry         0.5   0.4795
8      ipad         0.5   0.4795
11      now         0.5   0.4795
20      win         0.5   0.4795


## Question 4 (10 points):
Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [32]:
# You code here (Please add comments in the code):
# Import necessary libraries to work with BERT and cosine similarity
from transformers import BertTokenizer, BertModel
from sklearn.metrics.pairwise import cosine_similarity
import torch
import warnings
warnings.filterwarnings("ignore")

# Initialize BERT tokenizer and model
# We will use 'bert-base-uncased', a common pre-trained BERT model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# Define a function to get BERT embeddings (vector representation) for a piece of text
# This function tokenizes the input text and gets the BERT output embeddings
# We use 'torch.no_grad()' to avoid calculating gradients since we are only using the model for inference
def get_bert_embedding(text):
    inputs = tokenizer(text, return_tensors='pt', max_length=512, truncation=True, padding=True)  # Tokenize input text
    with torch.no_grad():  # We don't need to calculate gradients when using a pre-trained model for embeddings
        outputs = model(**inputs)  # Get the model output
    # 'last_hidden_state' is the final output of the BERT model
    # We take the mean of the output vectors along the sequence dimension to get a single vector for the entire text
    return outputs.last_hidden_state.mean(dim=1).squeeze()

# Prepare the text data (messages) that we want to rank by similarity to a query
messages = [
    "Win a free ipad. Click this link.",
    "Limited time offer! Click here to claim prize.",
    "Hello, are you there?",
    "Hurry now to claim prize!",
    "Click this link to claim a rare prize!",
    "What are you doing?"
]

# 1 = Spam, 0 = Not spam
labels = [1, 1, 0, 1, 1, 0]

# The query that we want to match the most relevant messages to
query = "Claim your free prize now"

# Get BERT embeddings for each of the messages in the list
# We use a list comprehension to iterate over each message and convert it to its BERT embedding
message_embeddings = [get_bert_embedding(message) for message in messages]

# Get the BERT embedding for the query
# We will compare this embedding with the message embeddings to find the most similar ones
query_embedding = get_bert_embedding(query)

# Calculate the cosine similarity between the query and each message
# Cosine similarity measures the similarity between two vectors by calculating the cosine of the angle between them
# The closer the cosine similarity is to 1, the more similar the vectors are
cosine_scores = [cosine_similarity(query_embedding.unsqueeze(0), message.unsqueeze(0)).item() for message in message_embeddings]

# Sort the messages by their similarity score in descending order (most similar first)
# We zip the messages and their corresponding similarity scores together, and sort them by the score
sorted_messages = sorted(zip(messages, cosine_scores), key=lambda x: x[1], reverse=True)

# Print the sorted messages along with their similarity scores
# We enumerate over the sorted messages to print them in a numbered list
print("Messages ranked by similarity to the query:")
for i, (message, score) in enumerate(sorted_messages, start=1):
    print(f"{i}. {message} (Similarity: {score:.4f})")


Messages ranked by similarity to the query:
1. Hurry now to claim prize! (Similarity: 0.7788)
2. Limited time offer! Click here to claim prize. (Similarity: 0.6713)
3. Click this link to claim a rare prize! (Similarity: 0.6499)
4. Win a free ipad. Click this link. (Similarity: 0.5913)
5. What are you doing? (Similarity: 0.5332)
6. Hello, are you there? (Similarity: 0.5086)


# Mandatory Question

**Important: Reflective Feedback on this exercise**

Please provide your thoughts and feedback on the exercises you completed in this assignment. Consider the following points in your response:

Learning Experience: Describe your overall learning experience in working on extracting features from text data. What were the key concepts or techniques you found most beneficial in understanding the process?

Challenges Encountered: Were there specific difficulties in completing this exercise?

Relevance to Your Field of Study: How does this exercise relate to the field of NLP?

**(Your submission will not be graded if this question is left unanswered)**



In [33]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:

I feel like I learned a tremendous amount in this module; more than in previous modules. I wonder if that is because I'm more familiar
with the subject or if the presentation was different. Either way, I found this to be a very interesting module.

The demonstration by Ms. Fengjiao was to the point and very informative. It was easy for me to follow and replicate when the time came.
I was confident implimenting these methods quickly in this exercise on questions 1 - 3.

Question 4 was the exception. That question was very difficult. I don't feel like it aligned to much of our discussion in class. This
question required a lot of research for me. I guess that is good and bad. I didn't realize it would take as much time as it did. I had
to use stackoverflow to understand which libraries to import and then it took me a long time to find a way to write the code. I still
never figured out how to get a token from huggingface.com. I did however figure out how to suppress the warning using:
import warnings
warnings.filterwarnings("ignore")
The code seems to work correctly so I'm happy with it.
'''

'\nPlease write you answer here:\n\nI feel like I learned a tremendous amount in this module; more than in previous modules. I wonder if that is because I\'m more familiar\nwith the subject or if the presentation was different. Either way, I found this to be a very interesting module.\n\nThe demonstration by Ms. Fengjiao was to the point and very informative. It was easy for me to follow and replicate when the time came.\nI was confident implimenting these methods quickly in this exercise on questions 1 - 3.\n\nQuestion 4 was the exception. That question was very difficult. I don\'t feel like it aligned to much of our discussion in class. This\nquestion required a lot of research for me. I guess that is good and bad. I didn\'t realize it would take as much time as it did. I had \nto use stackoverflow to understand which libraries to import and then it took me a long time to find a way to write the code. I still\nnever figured out how to get a token from huggingface.com. I did however f